### ISSUE TITLE
sql to sails conversion error

### ISSUE THREAD

**Issue by praveen4554** [juliandavidmr/sails-inverse-model#13]
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.exports.toSailsAttribute

**Comment by Islam-Baraka** [comment]
same is here

**Comment by juliandavidmr** [comment]
I need more details.

**Comment by Islam-Baraka** [comment]
to fix it please replace the following lines 
at /generator/mysql/compiler_mysql.js 
starting of line 35

```
    for (var colum in data[table].columns) {
              //console.log(table + "=>" + colum);
              var reference_fk = undefined;
              if (data2[colum] && data2[colum]["REFERENCED_TABLE_NAME"]) {
                reference_fk = {
                  table: data2[colum].REFERENCED_TABLE_NAME,
                  column: data2[colum].REFERENCED_COLUMN_NAME
                };
                //console.log(table + "=>" + JSON.stringify(data2[colum], null, 4));
              }
              var attributes = data[table].columns[colum];
              //console.log(attributes);
              var result = transpile(attributes, colum, reference_fk);
              view_contents.push(result.view_content);
              attributes_sails.push(result.model_content);
            }
```


the data returned from MySQL is in different structures of your main code 
data[table].columns => data[table][colum]
 
i think the issue is that we have an old version of MySql DB 
mine is Server version: 5.6.20 - MySQL Community Server (GPL) 
working on windows 


perhaps it's a good idea to check for both structures as I believe the tow are working 


right now i have another error on saving files 
ReferenceError: ansi is not defined
i will work on it

**Comment by gadonski** [comment]
Same error on mac os

**Comment by juliandavidmr** [comment]
We are working to make SIM better with the support of the community and major contributors such as @Islam-Baraka ... 

We will soon release a version with many fixes.
